Fix test_metadata_compatibility
This adds `3.3.x` between 2.3 and latest-nightly so that migration logic
on templates is run. Otherwise the test would fail with:

    IllegalArgumentException: Index patterns must not be null or empty;
    got null